package damien.nodeworks.block.entity

import damien.nodeworks.registry.ModBlockEntities
import damien.nodeworks.script.cpu.CpuRules
import net.minecraft.core.BlockPos
import net.minecraft.core.HolderLookup
import net.minecraft.nbt.CompoundTag
import net.minecraft.network.protocol.Packet
import net.minecraft.network.protocol.game.ClientGamePacketListener
import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.entity.BlockEntity
import net.minecraft.world.level.block.state.BlockState

/**
 * Buffer block (code name: CraftingStorage — kept for save-compat) — contributes
 * both count and unique-types capacity to an adjacent Crafting CPU.
 *
 * All tunables come from [CpuRules]; this class only tracks its own tier and delegates.
 */
class CraftingStorageBlockEntity(
    pos: BlockPos,
    state: BlockState
) : BlockEntity(ModBlockEntities.CRAFTING_STORAGE, pos, state), CpuComponentBlockEntity {

    /** The storage tier (1–4). */
    var tier: Int = CpuRules.MIN_TIER
        private set

    /** Count-axis capacity this block contributes to its CPU. */
    val storageCapacity: Long get() = CpuRules.bufferCount(tier)

    /** Unique-types capacity this block contributes to its CPU. */
    val storageTypes: Int get() = CpuRules.bufferTypes(tier)

    /** Heat generated by this block (Phase 4 will wire this into the Core). */
    val storageHeat: Int get() = CpuRules.bufferHeat(tier)

    fun setTier(newTier: Int) {
        tier = CpuRules.clampTier(newTier)
        setChanged()
        level?.sendBlockUpdated(worldPosition, blockState, blockState, Block.UPDATE_ALL)
        notifyAdjacentCores()
    }

    private fun notifyAdjacentCores() {
        val lvl = level ?: return
        // Walk the entire component chain so cores multiple blocks away still recalculate
        CpuComponentBlockEntity.findConnectedCores(lvl, worldPosition).forEach { it.recalculateCapacity() }
    }

    override fun setRemoved() {
        super.setRemoved()
        // Notification handled by the block's playerWillDestroy for clean-removal case
    }

    // --- Serialization ---

    override fun saveAdditional(tag: CompoundTag, registries: HolderLookup.Provider) {
        super.saveAdditional(tag, registries)
        tag.putInt("tier", tier)
    }

    override fun loadAdditional(tag: CompoundTag, registries: HolderLookup.Provider) {
        super.loadAdditional(tag, registries)
        tier = if (tag.contains("tier")) CpuRules.clampTier(tag.getInt("tier")) else CpuRules.MIN_TIER
    }

    override fun getUpdateTag(registries: HolderLookup.Provider): CompoundTag {
        return saveWithoutMetadata(registries)
    }

    override fun getUpdatePacket(): Packet<ClientGamePacketListener> {
        return ClientboundBlockEntityDataPacket.create(this)
    }
}
