package damien.nodeworks.block.entity

import damien.nodeworks.registry.ModBlockEntities
import damien.nodeworks.script.cpu.CpuRules
import net.minecraft.core.BlockPos
import net.minecraft.core.HolderLookup
import net.minecraft.nbt.CompoundTag
import net.minecraft.network.protocol.Packet
import net.minecraft.network.protocol.game.ClientGamePacketListener
import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.entity.BlockEntity
import net.minecraft.world.level.block.state.BlockState

/**
 * Stabilizer — provides cooling capacity to an adjacent Crafting CPU, balancing the heat
 * generated by higher-tier Buffers and Co-Processors. Excess cooling unlocks throttle bonuses
 * (overclocks the CPU); a cooling deficit drops throttle toward [CpuRules.THROTTLE_FLOOR].
 *
 * Tier controls cooling output; no heat generation.
 */
class StabilizerBlockEntity(
    pos: BlockPos,
    state: BlockState
) : BlockEntity(ModBlockEntities.STABILIZER, pos, state), CpuComponentBlockEntity {

    var tier: Int = CpuRules.MIN_TIER
        private set

    /** Cooling units this block contributes at its current tier. */
    val coolingContribution: Int get() = CpuRules.stabilizerCooling(tier)

    fun setTier(newTier: Int) {
        tier = CpuRules.clampTier(newTier)
        setChanged()
        level?.sendBlockUpdated(worldPosition, blockState, blockState, Block.UPDATE_ALL)
        notifyAdjacentCores()
    }

    private fun notifyAdjacentCores() {
        val lvl = level ?: return
        CpuComponentBlockEntity.findConnectedCores(lvl, worldPosition).forEach { it.recalculateCapacity() }
    }

    override fun saveAdditional(tag: CompoundTag, registries: HolderLookup.Provider) {
        super.saveAdditional(tag, registries)
        tag.putInt("tier", tier)
    }

    override fun loadAdditional(tag: CompoundTag, registries: HolderLookup.Provider) {
        super.loadAdditional(tag, registries)
        tier = if (tag.contains("tier")) CpuRules.clampTier(tag.getInt("tier")) else CpuRules.MIN_TIER
    }

    override fun getUpdateTag(registries: HolderLookup.Provider): CompoundTag {
        return saveWithoutMetadata(registries)
    }

    override fun getUpdatePacket(): Packet<ClientGamePacketListener> {
        return ClientboundBlockEntityDataPacket.create(this)
    }
}
