modLoader = "kotlinforforge"
loaderVersion = "[5,)"

license = "CC0-1.0"

[[mods]]
modId = "nodeworks"
version = "${version}"
displayName = "Nodeworks"
description = '''
Scripting-driven automation mod with node networks and Lua terminals.
'''

[[dependencies.nodeworks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nodeworks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
