package damien.nodeworks.script.cpu

/**
 * Single source of truth for every Crafting CPU tunable and formula.
 *
 * All constants, lookup tables, and math used by the multiblock CPU live here.
 * Nothing else (block entity, GUI, payload, diagnostic tool) should hold its own
 * copy of a buffer capacity, heat value, or throttle formula — everything reads
 * or calls into this object.
 *
 * See docs/design/crafting-cpu.md for the design spec (the *what* and *why* in prose).
 * This file is the *how* (constants and formulas).
 *
 * Deliberately pure Kotlin, no Minecraft imports. Makes the math trivially testable,
 * reviewable, and portable between loaders.
 */
object CpuRules {

    // =====================================================================
    // Tiers
    // =====================================================================

    const val MIN_TIER = 1
    const val MAX_TIER = 4

    /** Clamp any incoming tier value into the supported range. */
    fun clampTier(tier: Int): Int = tier.coerceIn(MIN_TIER, MAX_TIER)

    // =====================================================================
    // Buffer — count + types + heat, indexed by [tier - 1]
    // =====================================================================

    /** Item count capacity contributed by one Buffer block. Long-typed to stay safe
     *  when summed across many buffers in networks with billions of items. */
    val BUFFER_COUNT_BY_TIER = longArrayOf(64L, 256L, 1024L, 4096L)

    /** Unique item-type capacity contributed by one Buffer block. */
    val BUFFER_TYPES_BY_TIER = intArrayOf(4, 8, 16, 32)

    /** Heat generated by one Buffer block. T1 is deliberately free so early-game
     *  builds work without cooling infrastructure. */
    val BUFFER_HEAT_BY_TIER = intArrayOf(0, 4, 12, 24)

    /** Base buffer capacity the Core itself provides before any Buffer is connected.
     *  Lets a CPU with zero Buffer blocks handle trivial 1-2 item crafts. */
    const val CORE_BASE_COUNT: Long = 256L
    const val CORE_BASE_TYPES: Int = 2

    fun bufferCount(tier: Int): Long = BUFFER_COUNT_BY_TIER[clampTier(tier) - 1]
    fun bufferTypes(tier: Int): Int = BUFFER_TYPES_BY_TIER[clampTier(tier) - 1]
    fun bufferHeat(tier: Int): Int = BUFFER_HEAT_BY_TIER[clampTier(tier) - 1]

    // =====================================================================
    // Co-Processor — heat by tier, every one adds exactly 1 thread
    // =====================================================================

    /** Heat generated by one Co-Processor block. */
    val COPROCESSOR_HEAT_BY_TIER = intArrayOf(2, 4, 6, 8)

    /** Every Co-Processor adds exactly one parallel craft thread regardless of tier.
     *  Tier only affects heat generation. Open question Q1 in the plan flags this for
     *  possible revision if playtesting shows we need more tier depth. */
    const val THREADS_PER_COPROCESSOR: Int = 1

    fun coProcessorHeat(tier: Int): Int = COPROCESSOR_HEAT_BY_TIER[clampTier(tier) - 1]

    // =====================================================================
    // Stabilizer — cooling capacity by tier
    // =====================================================================

    /** Cooling capacity provided by one Stabilizer block. */
    val STABILIZER_COOLING_BY_TIER = intArrayOf(8, 24, 72, 200)

    fun stabilizerCooling(tier: Int): Int = STABILIZER_COOLING_BY_TIER[clampTier(tier) - 1]

    // =====================================================================
    // Substrate — direct contribution + adjacency bonus
    // =====================================================================

    /** Each Substrate block contributes a small amount of unique-type capacity on its own,
     *  independent of adjacency. Placing one is never pointless, even without synergy. */
    const val SUBSTRATE_TYPE_CONTRIBUTION: Int = 1

    /** Throttle multiplier added per Buffer/Co-Processor face touching Substrate.
     *  A Buffer with 3 Substrate-adjacent faces adds (3 × 0.10) = +30% to the CPU's throttle. */
    const val SUBSTRATE_BONUS_PER_FACE: Float = 0.10f

    // =====================================================================
    // Throttle math — the speed multiplier for every CPU operation
    // =====================================================================

    /** Hard minimum throttle. Severe heat deficit clamps here — CPU stays functional
     *  but visibly crippled, never completely frozen. */
    const val THROTTLE_FLOOR: Float = 0.25f

    /** Bonus per point of excess cooling capacity (cooling − heat_generated). */
    const val COOLING_BONUS_PER_EXCESS: Float = 0.05f

    /** Maximum throttle bonus from excess cooling alone. Prevents infinite Stabilizer stacking. */
    const val COOLING_BONUS_CAP: Float = 2.0f

    /** Maximum throttle bonus from Substrate adjacency alone. */
    const val SUBSTRATE_BONUS_CAP: Float = 4.0f

    /** Per-op-type base tick cost at throttle = 1.0×.
     *
     *  Crafting-table assembly is the most expensive op by design — at 1.00× throttle a
     *  basic Instruction Set takes 3 seconds, which gives the player a real reason to
     *  invest in cooling + substrate. Item-movement ops (Pull / Deliver) are cheaper —
     *  1 second at 1.00×. Process ops gate on external machine cook time already, so
     *  their scheduler cost is the same as item-movement.
     *
     *  All costs scale down as throttle^2 so full optimization (throttle ≈ 8×) drops
     *  even a 60-tick Execute to ~1 tick. See [opCost]. */
    const val EXECUTE_BASE_COST: Int = 60
    const val PULL_BASE_COST: Int = 20
    const val DELIVER_BASE_COST: Int = 20
    const val PROCESS_BASE_COST: Int = 20

    /**
     * Heat penalty multiplier — in the range [THROTTLE_FLOOR, 1.0].
     * Returns 1.0 exactly when cooling ≥ heat generated (no penalty).
     * Scales linearly with the deficit ratio, floored at [THROTTLE_FLOOR].
     */
    fun heatPenalty(heatGenerated: Int, heatCooled: Int): Float {
        if (heatGenerated <= 0) return 1.0f
        if (heatCooled >= heatGenerated) return 1.0f
        val deficit = (heatGenerated - heatCooled).toFloat() / heatGenerated.toFloat()
        return (1.0f - deficit).coerceAtLeast(THROTTLE_FLOOR)
    }

    /**
     * Cooling overclock bonus multiplier. Returns 1.0 if there is any heat deficit;
     * otherwise scales linearly with excess cooling, capped at [COOLING_BONUS_CAP].
     */
    fun coolingBonus(heatGenerated: Int, heatCooled: Int): Float {
        if (heatCooled < heatGenerated) return 1.0f
        val excess = heatCooled - heatGenerated
        val bonus = 1.0f + (excess * COOLING_BONUS_PER_EXCESS)
        return bonus.coerceAtMost(COOLING_BONUS_CAP)
    }

    /**
     * Substrate adjacency bonus multiplier.
     *
     * [adjacencyCount] = the total number of faces (across all Buffer and Co-Processor
     * blocks in the CPU) that physically touch a Substrate block. Each face counted once.
     * Substrate-to-Substrate faces do not count (Substrate is a conductor, not self-synergistic).
     */
    fun substrateBonus(adjacencyCount: Int): Float {
        val bonus = 1.0f + (adjacencyCount * SUBSTRATE_BONUS_PER_FACE)
        return bonus.coerceAtMost(SUBSTRATE_BONUS_CAP)
    }

    /**
     * The CPU's global throttle multiplier, composed multiplicatively:
     *
     *     throttle = substrate_bonus × cooling_bonus × heat_penalty
     *
     * heat_penalty < 1.0 will always dominate: an overheating CPU runs slow regardless
     * of how much Substrate synergy is applied. That is the intended gating mechanic.
     */
    fun throttle(substrateBonus: Float, coolingBonus: Float, heatPenalty: Float): Float {
        return substrateBonus * coolingBonus * heatPenalty
    }

    // =====================================================================
    // Op cost — whole-tick cost of one scheduled CPU operation
    // =====================================================================

    /**
     * Tick cost of a single CPU operation given its [baseCost] at 1.00× throttle and the
     * current multiplier. Scales quadratically so the throttle feels impactful: a 2× boost
     * quarters the cost, 8× cuts it by a factor of 64.
     *
     * Returns 0 at high enough throttle that the op can chain within the same tick —
     * an Execute op (base 60) hits 0 around throttle 8, matching the max theoretical
     * throttle (heat-perfect + cap cooling + cap substrate).
     */
    fun opCost(throttle: Float, baseCost: Int): Int {
        if (throttle <= 0f) return baseCost
        val scaled = (baseCost.toFloat() / (throttle * throttle)).toInt()
        return scaled.coerceAtLeast(0)
    }

    // =====================================================================
    // Safety caps
    // =====================================================================

    /** Max operations any single Core may execute per tick, across all its threads.
     *  Prevents pathological craft trees from freezing the server. Real crafts stay well under. */
    const val OPS_PER_TICK_CAP: Int = 256

    /** Max CPU component blocks (Buffer + Co-Processor + Substrate + Stabilizer) discoverable
     *  by one Core's BFS. Above this, a diagnostic warning surfaces and extra components are
     *  ignored. Chosen high enough to accommodate extreme endgame builds, low enough to bound
     *  BFS cost on chunk load. */
    const val COMPONENTS_PER_CPU_CAP: Int = 1024

    // =====================================================================
    // Suggestion engine — pure textual recommendations for the GUI
    // =====================================================================

    /**
     * Prioritized, player-facing recommendations for fixing a misconfigured CPU.
     * Returned in priority order (most impactful first). GUI displays all of them.
     */
    fun suggestions(
        heatGenerated: Int,
        heatCooled: Int,
        substrateAdjacencies: Int,
        hasBuffer: Boolean
    ): List<String> {
        val out = mutableListOf<String>()
        if (!hasBuffer) {
            out += "Add at least one Buffer block to enable crafting."
        }
        if (heatCooled < heatGenerated) {
            val deficit = heatGenerated - heatCooled
            val t1Cooling = STABILIZER_COOLING_BY_TIER[0]
            val stabilizersNeeded = (deficit + t1Cooling - 1) / t1Cooling
            val plural = if (stabilizersNeeded == 1) "" else "s"
            out += "Heat deficit: $deficit. Add $stabilizersNeeded Tier-1 Stabilizer$plural to reach 100% speed."
        }
        if (hasBuffer && substrateAdjacencies == 0) {
            out += "Place Substrate next to Buffers or Co-Processors for a throttle bonus."
        }
        return out
    }
}
