package damien.nodeworks.script.cpu

/**
 * Single source of truth for every Crafting CPU tunable and formula.
 *
 * All constants, lookup tables, and math used by the multiblock CPU live here.
 * Nothing else (block entity, GUI, payload, diagnostic tool) should hold its own
 * copy of a buffer capacity, heat value, or throttle formula — everything reads
 * or calls into this object.
 *
 * See docs/design/crafting-cpu.md for the design spec (the *what* and *why* in prose).
 * This file is the *how* (constants and formulas).
 *
 * Deliberately pure Kotlin, no Minecraft imports. Makes the math trivially testable,
 * reviewable, and portable between loaders.
 */
object CpuRules {

    // =====================================================================
    // Buffer — one block = fixed capacity + heat. No tiers.
    // =====================================================================

    /** Item count capacity contributed by one Buffer block. Long-typed to stay safe
     *  when summed across many buffers in networks with billions of items. */
    const val BUFFER_COUNT_CAPACITY: Long = 512L

    /** Unique item-type capacity contributed by one Buffer block. */
    const val BUFFER_TYPES_CAPACITY: Int = 8

    /** Heat generated by one Buffer block. Non-zero so the puzzle is present even
     *  for small/early-game CPUs — a 1-Buffer CPU needs at least one Stabilizer. */
    const val BUFFER_HEAT: Int = 2

    /** Base buffer capacity the Core itself provides before any Buffer is connected.
     *  Lets a CPU with zero Buffer blocks handle trivial 1-2 item crafts. */
    const val CORE_BASE_COUNT: Long = 256L
    const val CORE_BASE_TYPES: Int = 4

    // =====================================================================
    // Co-Processor — one block = one thread + fixed heat
    // =====================================================================

    /** Heat generated by one Co-Processor block. */
    const val COPROCESSOR_HEAT: Int = 3

    /** Every Co-Processor adds exactly one parallel craft thread. */
    const val THREADS_PER_COPROCESSOR: Int = 1

    // =====================================================================
    // Stabilizer — cluster bonus + sharing penalty
    // =====================================================================
    //
    // Each Stabilizer produces a total cooling output = base + (adjacent stabilizers × bonus).
    // Stabilizers amplify each other in a cluster (heatsink fins). The output is then
    // divided evenly across the heat-gen faces that Stabilizer touches — sharing a
    // Stabilizer between multiple heat-gens dilutes its cooling.
    //
    // This kills "cheese" layouts like a checkerboard of stabilizers (each stab surrounded
    // by 6 heat-gens gets output 1, divided by 6 = 0.17 cooling per neighbor) and rewards
    // heatsink-shaped clusters (interior stabilizers with many stab neighbors output more).

    /** Base cooling a lone Stabilizer (no stabilizer neighbors) puts out in total. */
    const val STABILIZER_BASE_COOLING: Float = 1.0f

    /** Extra cooling added per adjacent Stabilizer face. A Stabilizer in the middle of a
     *  wall (4 stab neighbors) outputs 1 + 4 = 5 cooling total. Max practical bonus is
     *  5 (a stabilizer with 6 stab neighbors can't also touch a heat-gen). */
    const val STABILIZER_CLUSTER_BONUS: Float = 1.0f

    // =====================================================================
    // Hotspot heat — dense heat-gen packing punishes itself
    // =====================================================================

    /** Extra heat added to a heat-gen for every face that touches another heat-gen.
     *  Makes blob/cube layouts exponentially worse (interior blocks have 6 heat-gen
     *  neighbors) and forces the player to spread heat-gens out or interleave Stabilizers
     *  between them. This is the primary anti-trivialization lever of the design. */
    const val HOTSPOT_HEAT_PER_FACE: Int = 1

    // =====================================================================
    // Substrate — direct contribution + adjacency bonus
    // =====================================================================

    /** Each Substrate block contributes a small amount of unique-type capacity on its own,
     *  independent of adjacency. Placing one is never pointless, even without synergy. */
    const val SUBSTRATE_TYPE_CONTRIBUTION: Int = 1

    /** Throttle multiplier added per Buffer/Co-Processor face touching Substrate.
     *  A Buffer with 3 Substrate-adjacent faces adds (3 × 0.10) = +30% to the CPU's throttle. */
    const val SUBSTRATE_BONUS_PER_FACE: Float = 0.10f

    // =====================================================================
    // Throttle math — the speed multiplier for every CPU operation
    // =====================================================================

    /** Hard minimum throttle. Severe heat deficit clamps here — CPU stays functional
     *  but visibly crippled, never completely frozen. */
    const val THROTTLE_FLOOR: Float = 0.25f

    /** Maximum throttle bonus from Substrate adjacency alone. Substrate is the ONLY
     *  mechanism that can push throttle above 1.0× — over-cooling no longer bonuses. */
    const val SUBSTRATE_BONUS_CAP: Float = 4.0f

    /** Per-op-type base tick cost at throttle = 1.0×.
     *
     *  Crafting-table assembly is the most expensive op by design — at 1.00× throttle a
     *  basic Instruction Set takes 3 seconds, which gives the player a real reason to
     *  invest in cooling + substrate. Item-movement ops (Pull / Deliver) are cheaper —
     *  1 second at 1.00×. Process ops gate on external machine cook time already, so
     *  their scheduler cost is the same as item-movement.
     *
     *  All costs scale down as throttle^2. Max achievable throttle is the substrate cap
     *  (4.0×), which drops Execute to 3 ticks and Pull/Deliver/Process to 1 tick. Execute
     *  has an intentional 3-tick floor at max throttle — crafting is never free. */
    const val EXECUTE_BASE_COST: Int = 60
    const val PULL_BASE_COST: Int = 20
    const val DELIVER_BASE_COST: Int = 20
    const val PROCESS_BASE_COST: Int = 20

    /**
     * Heat penalty multiplier — in the range [THROTTLE_FLOOR, 1.0].
     * Returns 1.0 exactly when cooling ≥ heat generated (no penalty).
     * Scales linearly with the deficit ratio, floored at [THROTTLE_FLOOR].
     */
    fun heatPenalty(heatGenerated: Int, heatCooled: Int): Float {
        if (heatGenerated <= 0) return 1.0f
        if (heatCooled >= heatGenerated) return 1.0f
        val deficit = (heatGenerated - heatCooled).toFloat() / heatGenerated.toFloat()
        return (1.0f - deficit).coerceAtLeast(THROTTLE_FLOOR)
    }


    /**
     * Substrate adjacency bonus multiplier.
     *
     * [adjacencyCount] = the total number of faces (across all Buffer and Co-Processor
     * blocks in the CPU) that physically touch a Substrate block. Each face counted once.
     * Substrate-to-Substrate faces do not count (Substrate is a conductor, not self-synergistic).
     */
    fun substrateBonus(adjacencyCount: Int): Float {
        val bonus = 1.0f + (adjacencyCount * SUBSTRATE_BONUS_PER_FACE)
        return bonus.coerceAtMost(SUBSTRATE_BONUS_CAP)
    }

    // =====================================================================
    // Op cost — whole-tick cost of one scheduled CPU operation
    // =====================================================================

    /**
     * Tick cost of a single CPU operation given its [baseCost] at 1.00× throttle and the
     * current multiplier. Scales quadratically so the throttle feels impactful: a 2× boost
     * quarters the cost.
     *
     * Max achievable throttle is the substrate cap (4.0×). At 4.0× an Execute (base 60)
     * drops to 3 ticks, and Pull/Deliver/Process (base 20) drop to 1 tick. Execute has
     * an intentional 3-tick floor even at max throttle.
     */
    fun opCost(throttle: Float, baseCost: Int): Int {
        if (throttle <= 0f) return baseCost
        val scaled = (baseCost.toFloat() / (throttle * throttle)).toInt()
        return scaled.coerceAtLeast(0)
    }

    // =====================================================================
    // Safety caps
    // =====================================================================

    /** Max operations any single Core may execute per tick, across all its threads.
     *  Prevents pathological craft trees from freezing the server. Real crafts stay well under. */
    const val OPS_PER_TICK_CAP: Int = 256

    /** Max CPU component blocks (Buffer + Co-Processor + Substrate + Stabilizer) discoverable
     *  by one Core's BFS. Above this, a diagnostic warning surfaces and extra components are
     *  ignored. Chosen high enough to accommodate extreme endgame builds, low enough to bound
     *  BFS cost on chunk load. */
    const val COMPONENTS_PER_CPU_CAP: Int = 1024

    // =====================================================================
    // Suggestion engine — pure textual recommendations for the GUI
    // =====================================================================

    /**
     * Prioritized, player-facing recommendations for fixing a misconfigured CPU.
     * Returned in priority order (most impactful first). GUI displays all of them.
     */
    fun suggestions(
        heatGenerated: Int,
        heatCooled: Int,
        substrateAdjacencies: Int,
        hasBuffer: Boolean
    ): List<String> {
        val out = mutableListOf<String>()
        if (!hasBuffer) {
            out += "Add at least one Buffer block to enable crafting."
        }
        if (heatCooled < heatGenerated) {
            val deficit = heatGenerated - heatCooled
            out += "Heat deficit: $deficit. Cluster Stabilizers together (walls/cubes) so each one cools better, and avoid sharing a Stabilizer between multiple heat-gens."
        }
        if (hasBuffer && substrateAdjacencies == 0) {
            out += "Place Substrate next to Buffers or Co-Processors for a throttle bonus."
        }
        return out
    }
}
